module Javascript.Keywords where

import Data.Set (Set)
import qualified Data.Set as Set
import Data.Text (Text, pack)

keywords :: Set Text
keywords =
  Set.fromList $
    map
      pack
      [ "abstract",
        "arguments",
        "async",
        "await",
        "boolean",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "class",
        "const",
        "continue",
        "debugger",
        "default",
        "delete",
        "do",
        "double",
        "else",
        "enum",
        "eval",
        "export",
        "extends",
        "false",
        "final",
        "finally",
        "float",
        "for",
        "function",
        "goto",
        "if",
        "implements",
        "function",
        "import",
        "in",
        "instanceof",
        "int",
        "interface",
        "let",
        "long",
        "native",
        "new",
        "null",
        "package",
        "private",
        "protected",
        "public",
        "return",
        "short",
        "static",
        "super",
        "switch",
        "synchronized",
        "this",
        "throw",
        "throws",
        "transient",
        "true",
        "try",
        "typeof",
        "using",
        "var",
        "void",
        "volatile",
        "while",
        "with",
        "yield"
      ]
